### PR TITLE
Docker-Compose.yaml to containerize all the docker build i.e. frontend, backend & flask code

### PR DESCRIPTION
**Pull request by sanvidpunde**
Docker-Compose.yaml to containerize all the docker build i.e. frontend, backend & flask code

### CODE REVIEW

**Review by RahulKrishnaGajula — APPROVED** [review]
Great work building the docker architecture!

**Comment by sanvidpunde** [comment]
> Great work building the docker architecture!

Docker compose will run all the images builds as a container which were created using docker files in backend, frontend & flask API webserver

**Comment by MayuriBhoyar04** [comment]
Good work on Docker

**Comment by sanvidpunde** [comment]
@MayuriBhoyar04 why did you reponed this pr!!!
Please approve it or it will screw up the structure of git file !!!
Fast

**Review by themehulprajapati — APPROVED** [review]

**Review by MayuriBhoyar04 — APPROVED** [review]
Good Work on Docker

**Pull request merged**
