### PR TITLE
Page for users to select filters

### PR DESCRIPTION
**Pull request by RahulKrishnaGajula**
This page will have a list of filters that users can choose in order to get course recommendation

### CODE REVIEW

**Review by sanvidpunde — APPROVED** [review]
Do we need to change images in the next commit? I guess they look okish.

**Review by RakshithGonsalves — APPROVED** [review]
Hi Rahul,
Maybe for next time, change the CAO number to a text box from a dropdown.

**Comment by RahulKrishnaGajula** [comment]
> Do we need to change images in the next commit? I guess they look okish.

Will keep looking for images for future commits

**Review by sanvidpunde — APPROVED** [review]

**Comment by RahulKrishnaGajula** [comment]
> Hi Rahul, Maybe for next time, change the CAO number to a text box from a dropdown.

Noted, it cant be a dropdown, thats right

**Review by RakshithGonsalves — COMMENTED** [review]
The UI looks nice. Go Ahead with the changes

**Pull request merged**
