### PR TITLE
Adding updated Tableau Dashboard

### PR DESCRIPTION
**Pull request by siddheshpatil28**
Adding Updated Tableau Dashboard based on Yelp Reviews Added in the dataset.

### CODE REVIEW

**Comment by siddheshpatil28** [comment]
Dashboard 1

**Comment by RahulKrishnaGajula** [comment]
Hi Siddhesh, just a couple of suggestions on this,

1. Would it be possible to rename the word sentiment to reviews because sentiment is a relatively technical term and not all of our users may understand it?
2. The heatmap on the left: would it be possible to enlarge it so that the university names are visible on the visualization instead of it being visible only when the user hovers over it? You may have to remove one graph from the dashboard. maybe the yearwise sentiment count as its not really meaningful for the users to know how many reviews are collected per year?


Just my suggestions.

@sanvidpunde 
@RakshithGonsalves @MayuriBhoyar04 @themehulprajapati what do you guys think?

**Comment by sanvidpunde** [comment]
Is it possible to make it less cluttered? end users are students so they might get overwhelmed with the info on screen

**Review by RakshithGonsalves — APPROVED** [review]

**Review by MayuriBhoyar04 — APPROVED** [review]
The dashboard are quite good gives proper information.

**Comment by siddheshpatil28** [comment]
Hi @RahulKrishnaGajula, thanks a lot for suggestions. Will update the dashboard with less cluttering.

**Pull request merged**
