### PR TITLE
Website Frontend User Auth & Psychometric Test Stepper Form

### PR DESCRIPTION
**Pull request by themehulprajapati**
This commit contains all responsible frontend code for Login, Signup page; Psychometric Test Stepper Form and Simulation page.

### CODE REVIEW

**Comment by sanvidpunde** [comment]
Changes looks good for frontend. 
I will update the backend code by today.

**Review by sanvidpunde — APPROVED** [review]

**Comment by sanvidpunde** [comment]
@paul-kelly-dit 
Hi Paul,
I added a new  PR with Commit in this same PR with the backend code for the frontend code provided by Mehul rather than creating a new PR as The code depends on each other.

**Review by themehulprajapati — COMMENTED** [review]
Looks good.

**Comment by Therahul27** [comment]
Great Progress guys, This looks great

**Review by Therahul27 — APPROVED** [review]

**Review by siddheshpatil28 — COMMENTED** [review]
looks great! Good to go!

**Pull request merged**
