### PR TITLE
Added Our Lecturers Dynamic Page

### PR DESCRIPTION
**Pull request by themehulprajapati**
Designed Lecturers Dynamic Page:

- Imported professors.json data inside MongoDB
- Created GET endpoint at '/api/professor' which gives all records for professors
- On frontend added condition if staff thumbnail url not found replace with dummyImage of dimension 350*220

image

### CODE REVIEW

**Comment by RahulKrishnaGajula** [comment]
Hi Mehul, is it possible to get the lecturer's images?

**Comment by RakshithGonsalves** [comment]
Hi, Mehul, can we add a clipart?

**Comment by themehulprajapati** [comment]
> Hi Mehul, is it possible to get the lecturer's images?

Yeah for this we will need to find lecturer's image and upload somewhere let's say our project's s3 bucket; use this url for json data and it will work

**Comment by themehulprajapati** [comment]
> Hi, Mehul, can we add a clipart?

Yeah, better idea than dummy image

**Review by sanvidpunde — APPROVED** [review]

**Comment by sanvidpunde** [comment]
> 
in the university data
We have a column with professor image urls

**Review by RahulKrishnaGajula — APPROVED** [review]

**Comment by themehulprajapati** [comment]
> > @themehulprajapati
> > in the university data
> > We have a column with professor image urls
> > So almost all clg's professors have a image in dataset (both json and csv)

Okay, will look into it

**Pull request merged**
