### PR TITLE
Simulation Page

### PR DESCRIPTION
**Pull request by themehulprajapati**
Created 6 inputs CAO points (number from 0-6250, Field of Interest (select dropdown with single select), City (select dropdown with multi-select), Preferred Job Domain (select dropdown with single select), Hobbies (select dropdown with multi-select) and Spending Limit (select dropdown with single select).
Added frontend and Backend Form Validations.
Created API endpoint to accept all inputs.
Axios post request to this API with all input data.

### CODE REVIEW

**Review by RakshithGonsalves — CHANGES_REQUESTED** [review]
Hi Mehul,
Can you also add a screen shot, for it to be clear?

**Comment by themehulprajapati** [comment]
> Hi Mehul, Can you also add a screen shot, for it to be clear?
Sure Rakshith
image

**Review by RakshithGonsalves — APPROVED** [review]
Hi Mehul,
Looks good. Guess it's the interest profiler next.

**Review by RahulKrishnaGajula — APPROVED** [review]
Looks good man, Let me know if you need further inputs for the interest profiler to make the front-end

**Pull request merged**
