### PR TITLE
This script will generate data manually using existing dataset, 

### PR DESCRIPTION
**Pull request by MayuriTUD**
This script will generate data manually using existing dataset. This is done as there is lack of data availability or our project, so we are generating practice data.

### CODE REVIEW

**Review by sanvidpunde — APPROVED** [review]
For now, only a limited number of columns are present as per the code. I hope in the next commit you will add further columns.

**Comment by RakshithGonsalves** [comment]
How accurate will the data be when generated? As I remember we used the CAO data to generate this.

**Comment by sanvidpunde** [comment]
> How accurate will the data be when generated? As I remember we used the CAO data to generate this.

Yeah, Is it possible to verify the data accuracy as well?

**Review by Therahul27 — APPROVED** [review]
Please advice if any help is needed, I'll be more than happy to assist you with this

**Review by RakshithGonsalves — APPROVED** [review]
Need to work with more data in the coming weeks.

**Pull request merged**
