### PR TITLE
Sentiment Review Dashboard

### PR DESCRIPTION
**Pull request by themehulprajapati**
- This commit fixes one of the critical error from CourseDetails page.

- Main purpose of this commit was supposed to add Tableau Dashboard on UI but it could not be done yet as Tableau public website has "x-frame-options" header set to "sameorigin"

### CODE REVIEW

**Review by RakshithGonsalves — APPROVED** [review]

**Comment by RahulKrishnaGajula** [comment]
Hi Mehul, as you mentioned that the dashboard is not visible on the website now, is there a temporary workaround for this? maybe an external link? or even a screenshot of the dashboard? till we can integrate the actual dashboard

**Comment by themehulprajapati** [comment]
> Hi Mehul, as you mentioned that the dashboard is not visible on the website now, is there a temporary workaround for this? maybe an external link? or even a screenshot of the dashboard? till we can integrate the actual dashboard

Hi Rakshith, we can do 2 things either add a screenshot or add a hyperlink which will open Tableau public website. Need suggestion guys for this

**Comment by RahulKrishnaGajula** [comment]
I think the link would be better
As the users can at least interact with the dashboard

**Comment by RahulKrishnaGajula** [comment]
Please add the link together in this PR and we can close it

**Review by sanvidpunde — APPROVED** [review]

**Comment by themehulprajapati** [comment]
> Please add the link together in this PR and we can close it

Done

**Comment by RahulKrishnaGajula** [comment]
Nice, Thank you!

**Pull request merged**
