### PR TITLE
Added Footer, Splash Screen Animation

### PR DESCRIPTION
**Pull request by themehulprajapati**

### CODE REVIEW

**Review by RakshithGonsalves — CHANGES_REQUESTED** [review]
The Maximum Points for CAO is 625, not 500.
Other than that the UI looks good

**Review by RahulKrishnaGajula — CHANGES_REQUESTED** [review]
Hi Mehul, Please edit the following. CAO points maximum is 625 not 500. I noticed that there are certain places in the code that mention CAO points cannot exceed 500. Please change that.

Thank you

**Review by sanvidpunde — APPROVED** [review]
Hi Mehul,
I am assuming you changed the cao limit to 625, If not kindly change in next merge

**Review by themehulprajapati — COMMENTED** [review]
Updated all form input fields for Simulation page.
CAO points updated to have values from 0 - 625 only.

**Review by sanvidpunde — APPROVED** [review]

**Review by MayuriBhoyar04 — APPROVED** [review]
Good!!

**Review by siddheshpatil28 — APPROVED** [review]

**Review by RahulKrishnaGajula — APPROVED** [review]

**Pull request merged**
