### PR TITLE
Data Genration Code

### PR DESCRIPTION
**Pull request by siddheshpatil28**

### CODE REVIEW

**Review by MayuriBhoyar04 — APPROVED** [review]
Good Work

**Review by sanvidpunde — CHANGES_REQUESTED** [review]
Siddhesh
This Pr is more than 30 commits behind the main branch
This Pr if approved can delete the pre-existing structure 

Please do a new git pull and this will update the commits from the last 5 days

- Can you push this code inside this folder **MyUniLifeSimulation/Data/Data Generation/** after doing git pull
If you need help ask me or rahul

**Review by themehulprajapati — CHANGES_REQUESTED** [review]
Please take pull from main before this branch is merged into main. Thanks!

**Comment by siddheshpatil28** [comment]
I'll do it right away and update it. Thanks!

**Pull request closed without merging**
