### PR TITLE
New dataset for the recommender system. 

### PR DESCRIPTION
**Pull request by RahulKrishnaGajula**
This has the university name, course name, course code, CAO requirements, and Fee requirement.
image

### CODE REVIEW

**Review by sanvidpunde — APPROVED** [review]
Yay!
This dataset has a proper CAO score from what I checked. In the future, we should also aim to add extra columns.
good Work!

**Comment by sanvidpunde** [comment]
For the next merge can you specify if the dataset had the budget  column in euro? It will be helpful.

**Review by RakshithGonsalves — APPROVED** [review]
Hi Rahul,
Looks really nice, we may need more later on to create more options. This data can run parallel with the output of the recommenders.

**Comment by RahulKrishnaGajula** [comment]
> 

Will do, thanks for the lookout

**Pull request merged**
